DROP TYPE IF EXISTS game_type;
CREATE TYPE game_type AS ENUM (
  'Abstract',
  'Childrens',
  'Customizable',
  'Family',
  'Party',
  'Strategy',
  'Thematic',
  'Wargames'
);

CREATE TABLE meeple_boardgames (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  image TEXT,
  title TEXT NOT NULL,
  tagline TEXT NOT NULL,
  description TEXT NOT NULL,
  bg_type game_type NOT NULL,
  num_players TEXT NOT NULL,
  date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);