DROP TYPE IF EXISTS game_type;
CREATE TYPE game_type AS ENUM (
  'Abstract',
  'Childrens',
  'Customizable',
  'Family',
  'Party',
  'Strategy',
  'Thematic',
  'Wargames'
);

CREATE TABLE boardgames (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title VARCHAR(50) NOT NULL,
  tagline VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  type game_type NOT NULL,
  minimum_players INTEGER NOT NULL,
  maximum_players INTEGER NOT NULL,
  date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);