DROP TYPE IF EXISTS owner_status;
CREATE TYPE owner_status AS ENUM (
  'Own',
  'Want',
  'Sell'
);

CREATE TABLE collections (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  boardgame_id INTEGER REFERENCES boardgames(id) ON DELETE CASCADE NOT NULL,
  rating INTEGER DEFAULT 0,
  play_count INTEGER NOT NULL DEFAULT 0,
  owner_status owner_status,
  date_created TIMESTAMPTZ NOT NULL DEFAULT now() 
);